### ISSUE TITLE
Tim

### ISSUE THREAD

**Issue by alexnsu** [timsl/agp-grus#1]
Alex finns, kan någon fika?

**Comment by timsl** [comment]
Fixed

**Comment by timsl** [comment]
?done

________________________________
Från: Alex Sundström <notifications@github.com>
Skickat: den 12 december 2017 14:10
Till: timsl/agp-grus
Kopia: Subscribed
Ämne: [timsl/agp-grus] Tim (#1)


Tim finns, kan någon fixa?

-

**Comment by KonradMagnusson** [comment]
BROKEN RULES OK LOCKING CONV

**Comment by timsl** [comment]
Pls
